services:
  auth:
    image: quay.io/keycloak/keycloak
    ports:
      - "8180:8180"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --http-port=8180
    #   - --import-realm
    volumes:
      - keycloak-data:/opt/keycloak/data
    #   - /home/keycloak/realm.json:/opt/keycloak/data/import/realm.json
  yugabyte:
    image: yugabytedb/yugabyte:latest
    ports:
      - 7000:7000
      - 9000:9000
      - 5433:5433
      - 9042:9042
    command:
      - bin/yugabyted
      - start
      - --base_dir=/home/yugabyte/yb_data
      - --daemon=false
    volumes:
      - yugabyte-data:/home/yugabyte/yb_data

volumes:
  keycloak-data:
  yugabyte-data:
