services:
  auth:
    image: quay.io/keycloak/keycloak
    ports:
      - "8180:8180"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --http-port=8180
    #   - --import-realm
    volumes:
      - keycloak-data:/opt/keycloak/data
    #   - /home/keycloak/realm.json:/opt/keycloak/data/import/realm.json

volumes:
  keycloak-data:
